
name: thiefmd
version: 0.1.0
grade: stable
adopt-info: thiefmd
summary: The markdown editor worth stealing.
license: GPL-3.0+
description: |
  Keep your Markdown managed. Write epic tales, keep a journal, or finally write that book report.
  ThiefMD is a Markdown Editor providing an easy way to organize your markdown documents.

base: core20
confinement: devmode

architectures:
  - build-on: amd64
  - build-on: i386

apps:
  thiefmd:
    command: usr/bin/com.github.kmwallio.thiefmd
    extensions: [gnome-3-28]
    plugs:
      - home
      - gsettings
      - x11
      - network
    slots:
      - dbus-daemon
    common-id: com.github.kmwallio.thiefmd
    environment:
      GSETTINGS_SCHEMA_DIR: $SNAP/share/glib-2.0/schemas
      GTK_USE_PORTAL: "1"

parts:
  valac:
    plugin: nil
    build-packages:
      - software-properties-common
    override-build: |
      echo "deb http://ppa.launchpad.net/vala-team/next/ubuntu xenial main" | tee /etc/apt/sources.list.d/vala-team.list
      apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 008940d610e4cd892340ab0a4ce987b57daac99c
      apt update
      apt upgrade -yy
    prime: [-*]
  thiefmd:
    after: [valac]
    plugin: meson
    source: https://github.com/kmwallio/ThiefMD.git
    source-branch: master
    meson-parameters: [--prefix=/snap/thiefmd/current/usr]
    build-packages:
      - valac-0.48
      - valac-bin
      - cmake
      - valadoc
      - libvaladoc-dev
      - gettext
      - libgee-0.8-dev
      - libgtk-3-dev
      - libgranite-dev
      - libglib2.0-dev
      - libgtkspell3-3-dev
      - libgtksourceview-4-dev
      - libwebkit2gtk-4.0-dev
      - libmarkdown2-dev
      - libxml2-dev
      - libgudev-1.0-dev
      - libclutter-1.0-dev
      - libarchive-dev
    stage-packages:
      - pandoc
    organize:
      snap/foliate/current/usr: usr
    parse-info: [usr/share/metainfo/com.github.kmwallio.thiefmd.appdata.xml]

slots:
  dbus-daemon:
    interface: dbus
    bus: session
    name: com.github.kmwallio.thiefmd
